package lv.kitn.generator;

public enum BuildingGroup {
  BG_MANUFACTURING,

  BG_LIGHT_INDUSTRY,
  BG_ARMS_INDUSTRIES,
  BG_ARTILLERY_FOUNDARIES,

  BG_HEAVY_INDUSTRY,
  BG_MILITARY_SHIPYARDS,
  BG_MUNITION_PLANTS,
  BG_SHIPYARDS,

  BG_AGRICULTURE,
  BG_RYE_FARMS,
  BG_WHEAT_FARMS,
  BG_RICE_FARMS,
  BG_MAIZE_FARMS,
  BG_MILLET_FARMS,
  BG_SUBSISTENCE_AGRICULTURE,
  BG_VINEYARD_PLANTATIONS,

  BG_RANCHING,
  BG_LIVESTOCK_RANCHES,
  BG_SUBSISTENCE_RANCHING,

  BG_PLANTATIONS,
  BG_COFFEE_PLANTATIONS,
  BG_COTTON_PLANTATIONS,
  BG_SILK_PLANTATIONS,
  BG_DYE_PLANTATIONS,
  BG_OPIUM_PLANTATIONS,
  BG_TEA_PLANTATIONS,
  BG_TOBACCO_PLANTATIONS,
  BG_SUGAR_PLANTATIONS,
  BG_BANANA_PLANTATIONS,

  BG_MINING,
  BG_GOLD_FIELDS,
  BG_GOLD_MINING,
  BG_COAL_MINING,
  BG_IRON_MINING,
  BG_LEAD_MINING,
  BG_SULFUR_MINING,

  BG_URBAN_FACILITIES,
  BG_ARTS,
  BG_TRADE,

  BG_GOVERNMENT,
  BG_TECHNOLOGY,
  BG_BUREAUCRACY,
  BG_SKYSCRAPER,
  BG_MONUMENTS,

  BG_INFRASTRUCTURE,
  BG_PUBLIC_INFRASTRUCTURE,
  BG_CONSTRUCTION,
  BG_PRIVATE_INFRASTRUCTURE,
  BG_CANALS,

  BG_MILITARY,
  BG_ARMY,
  BG_CONSCRIPTION,
  BG_NAVY,

  BG_LOGGING,
  BG_RUBBER,
  BG_WHALING,
  BG_FISHING,
  BG_OIL_EXTRACTION,
  BG_SERVICE,
  BG_POWER,
  BG_MONUMENTS_HIDDEN,
}
