name: GraalVM Native Image build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  buildOnWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - uses: microsoft/setup-msbuild@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: mvn -DskipTests -B clean package native-image:native-image --file pom.xml
        shell: powershell
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3.0.0
        with:
          version: latest
          file: target/victoria-3-map-randomizer-*.exe
          args: '-7'
      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: warn
          name: package
          path: target/*.exe

  buildOnMac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: mvn -DskipTests -B clean package native-image:native-image --file pom.xml
      - name: Run UPX
        uses: svenstaro/upx-action@2.4.1
        with:
          file: target/victoria-3-map-randomizer-*
          args: '-7'
      - name: Upload artifacts
        run: rm -rf victoria-3-map-randomizer-*.jar && mkdir staging && for file in victoria-3-map-randomizer-*; do cp "$file" "${file}-amd64"; done
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: staging

  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: mvn -DskipTests -B clean package native-image:native-image --file pom.xml
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3.0.0
        with:
          version: latest
          file: target/victoria-3-map-randomizer-*
          args: '-7'
      - name: Upload artifacts
        run: rm -rf victoria-3-map-randomizer-*.jar && mkdir staging && for file in victoria-3-map-randomizer-*; do cp "$file" "${file}-amd64"; done
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: staging

