name: GraalVM Native Image build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        run: mvn -DskipTests -B clean package
      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: target/victoria-3-map-randomizer-*.jar
          generate_release_notes: true
          make_latest: true

